// Generated by CoffeeScript 1.7.1
(function() {
  define(['editor', 'signin', 'DisplayPosts', '../../bower_components/marked/lib/marked', 'Routes'], function(Editor, SignIn, DisplayPosts, marked, Routes) {
    var App;
    App = (function() {
      function App(dataSource) {
        var displayPage, editor, routes, signin;
        this.dataSource = dataSource != null ? dataSource : {};
        marked.setOptions({
          renderer: new marked.Renderer(),
          gfm: true,
          tables: true,
          breaks: false,
          pedantic: false,
          sanitize: true,
          smartLists: true,
          smartypants: false
        });
        signin = new SignIn(this.dataSource);
        editor = new Editor(marked, this.dataSource);
        displayPage = new DisplayPosts(this.dataSource, marked);
        routes = new Routes(this.dataSource);
        return this;
      }

      return App;

    })();
    return App;
  });

}).call(this);
