// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function() {
    var BlogPost;
    BlogPost = (function() {
      function BlogPost(id, title, body, tags, author, date, marked) {
        this.id = id != null ? id : '';
        this.title = title != null ? title : '';
        this.body = body != null ? body : '';
        this.tags = tags != null ? tags : '';
        this.author = author != null ? author : '';
        this.date = date != null ? date : '';
        this.marked = marked != null ? marked : {};
        this.display = __bind(this.display, this);
        return this;
      }

      BlogPost.prototype.template = '<article>' + '<h3 class=\'title\'>{title}</h3>' + '<p class=\'body\'>{body}</p>' + '<div class=\'author\'>{author}</div>' + '<div class=\'tags\'>{tags}</div>' + '<div class=\'date\'>{date}</div>';

      BlogPost.prototype.display = function(post) {
        var output;
        output = tempate.replace('{title}', post.title);
        output += tempate.replace('{body}', this.marked(post.body));
        output += tempate.replace('{author}', post.author);
        output += tempate.replace('{tags}', post.tags);
        output += tempate.replace('{date}', post.date);
        return output;
      };

      return BlogPost;

    })();
    return BlogPost;
  });

}).call(this);
