// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var BlogPost;
    BlogPost = (function() {
      function BlogPost(title, body, tags, author, date) {
        this.title = title != null ? title : "";
        this.body = body != null ? body : "";
        this.tags = tags != null ? tags : "";
        this.author = author != null ? author : "";
        this.date = date != null ? date : "";
        return this;
      }

      return BlogPost;

    })();
    return BlogPost;
  });

}).call(this);
