// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function() {
    var DataSource;
    DataSource = (function() {
      function DataSource(_source) {
        this._source = _source != null ? _source : {};
        this.get = __bind(this.get, this);
        this.remove = __bind(this.remove, this);
        this.update = __bind(this.update, this);
        this.create = __bind(this.create, this);
        return this;
      }

      DataSource.prototype.login = function(user, pass) {
        this._source.login({
          user: user,
          pass: pass
        });
      };

      DataSource.prototype.create = function(item) {
        return this._source.create(item);
      };

      DataSource.prototype.update = function(item) {
        return this.source.update(item);
      };

      DataSource.prototype.remove = function(item) {
        return this._source.remove(item);
      };

      DataSource.prototype.get = function(id) {
        if (id) {
          return this._source.get(id);
        } else {
          return this._source.getAll();
        }
      };

      return DataSource;

    })();
    return DataSource;
  });

}).call(this);
