// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['../../bower_components/marked/lib/marked', 'BlogPost', '../../bower_components/localforage/dist/localforage'], function(marked, BlogPost, localForage) {
    var Editor;
    Editor = (function() {
      function Editor(ds, markdownEditor) {
        this.ds = ds != null ? ds : {};
        this.markdownEditor = markdownEditor != null ? markdownEditor : {};
        this.onComplete = __bind(this.onComplete, this);
        this.savePost = __bind(this.savePost, this);
        this.startAutoSave = __bind(this.startAutoSave, this);
        this.submitMarkdown = __bind(this.submitMarkdown, this);
        $('.btn-submit').on('click', this.submitMarkdown);
        $('.title, .body').on('keyup', this.startAutoSave);
        return this;
      }

      Editor.prototype.submitMarkdown = function(e) {
        var blogPost;
        blogPost = {
          title: $('.title').val(),
          body: $('.body').val(),
          tags: $('.tags').val(),
          author: $('.author').val(),
          date: moment()
        };
        this.ds.create(blogPost);
        $('.editor input, .editor textarea').val('');
        window.location.hash = '#/';
      };

      Editor.prototype.startAutoSave = function(e) {
        var autoSave;
        $('.title, .body').off('keyup', this.startAutoSave);
        this.savePost();
        autoSave = setTimeout((function(_this) {
          return function() {
            _this.savePost();
          };
        })(this), 5000);
      };

      Editor.prototype.savePost = function() {
        var blogPost;
        blogPost = {
          title: $('.title').val(),
          body: marked($('.body').val()),
          tags: $('.tags').val(),
          author: $('.author').val(),
          date: moment()
        };
        localForage.setItem('currentPost', blogPost);
      };

      Editor.prototype.onComplete = function(err, data) {
        if ((err != null) || data.success === false) {
          $('.editor error').show();
          $('.editor error').text("Could Not Add Resource");
        } else {
          $('.editor error').hide();
        }
      };

      return Editor;

    })();
    return Editor;
  });

}).call(this);
