// Generated by CoffeeScript 1.7.1
(function() {
  require(['editor', '../../bower_components/marked/lib/marked'], function(Editor, marked) {
    var App, app;
    App = (function() {
      function App() {
        var editor;
        marked.setOptions({
          renderer: new marked.Renderer(),
          gfm: true,
          tables: true,
          breaks: false,
          pedantic: false,
          sanitize: true,
          smartLists: true,
          smartypants: false
        });
        editor = new Editor(marked);
        return this;
      }

      return App;

    })();
    app = new App();
  });

}).call(this);
