// Generated by CoffeeScript 1.7.1
(function() {
  define(['app', 'DataSource', 'GithubSource'], function(App, DataSource, GithubSource) {
    var app, ds;
    ds = new DataSource(new GithubSource());
    app = new App(ds);
    return app;
  });

}).call(this);
