// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function() {
    var Routes;
    return Routes = (function() {
      function Routes(ds) {
        var routes;
        this.ds = ds != null ? ds : {};
        this._hideAll = __bind(this._hideAll, this);
        this.post = __bind(this.post, this);
        this.edit = __bind(this.edit, this);
        this.main = __bind(this.main, this);
        routes = {
          '/': this.main,
          '/edit': this.edit,
          '/edit/:id': this.edit,
          '/display/:id': this.post
        };
        this.router = Router(routes);
        this.router.init();
        return this;
      }

      Routes.prototype.main = function() {
        this._hideAll();
        $('.posts').parent().show();
        return this;
      };

      Routes.prototype.edit = function(id) {
        var $editor, post;
        $editor = $('.editor');
        this._hideAll();
        $editor.parent().show();
        if (id != null) {
          post = this.ds.get(id);
          $editor.find('.title').val(post.title);
          $editor.find('.body').val(post.body);
          $editor.find('.author').val(post.author);
          $editor.find('.tags').val(post.tags);
        }
        $editor.show();
        return this;
      };

      Routes.prototype.post = function(id) {
        var $post, post;
        $post = $('.post');
        this._hideAll();
        if (id != null) {
          post = this.ds.get(id);
          $post.find('.title').val(post.title);
          $post.find('.body').val(post.body);
          $post.find('.author').val(post.author);
          $post.find('.tags').val(post.tags);
          return $post.find('.date').val(post.date);
        } else {
          return this.router.setRoute('/');
        }
      };

      Routes.prototype._hideAll = function() {
        return $('.row').hide();
      };

      return Routes;

    })();
  });

}).call(this);
