// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['DataSource'], function(dataSource) {
    var SignIn;
    SignIn = (function() {
      function SignIn(ds) {
        this.ds = ds != null ? ds : {};
        this.doSignIn = __bind(this.doSignIn, this);
        $('.btn-signin').on('click', this.doSignIn);
        return this;
      }

      SignIn.prototype.doSignIn = function(e) {
        this.ds.login($('.user').val(), $('.pass').val());
        return this;
      };

      return SignIn;

    })();
    return SignIn;
  });

}).call(this);
